version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "12:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: snyk
    versions:
    - 1.440.1
    - 1.440.2
    - 1.440.4
    - 1.441.0
    - 1.445.0
    - 1.447.0
    - 1.448.0
    - 1.452.0
    - 1.454.0
    - 1.455.0
    - 1.456.0
    - 1.457.0
    - 1.458.0
    - 1.459.0
    - 1.460.0
    - 1.463.0
    - 1.466.0
    - 1.467.0
    - 1.473.0
    - 1.476.0
    - 1.479.0
    - 1.483.0
    - 1.487.0
    - 1.490.0
    - 1.493.0
    - 1.496.0
    - 1.500.0
    - 1.503.0
    - 1.506.0
    - 1.509.0
    - 1.512.0
    - 1.514.0
    - 1.519.0
    - 1.521.0
    - 1.522.0
    - 1.525.0
    - 1.526.0
    - 1.529.0
    - 1.530.0
    - 1.531.0
    - 1.535.0
    - 1.540.0
    - 1.542.0
    - 1.554.0
    - 1.561.0
    - 1.563.0
    - 1.565.0
    - 1.566.0
    - 1.567.0
    - 1.571.0
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.27
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: "@google-cloud/firestore"
    versions:
    - 4.10.0
    - 4.9.1
    - 4.9.2
    - 4.9.3
    - 4.9.4
    - 4.9.6
    - 4.9.7
    - 4.9.8
    - 4.9.9
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: bl
    versions:
    - 4.0.4
  - dependency-name: firebase-functions
    versions:
    - 3.13.1
  - dependency-name: lodash
    versions:
    - 4.17.20
